### ISSUE TITLE
Cambios SAT V1.2

### ISSUE THREAD

**Issue by yiyoMX** [AndresRamos/ARSoftware.Cfdi.DescargaMasiva#1]
Hola, hace unos dias se implementaron unos cambios en la api por parte del SAT para la descarga masiva, lo cual hace que esta api quede obsoleta, vas a actualizar para integrar los cambios?

**Comment by AndresRamos** [comment]
Si estoy planeando en actualizar el proyecto para implementar los cambios nuevos. Espero este fin de semana poder empezar.

**Comment by AndresRamos** [comment]
Se hizo merge el pull request #3.
La implementacion de los nuevos cambios se estan haciendo en el branch development.
