### ISSUE TITLE
Error al enviar solicitud por UUID

### ISSUE THREAD

**Issue by AndresRamos** [AndresRamos/ARSoftware.Cfdi.DescargaMasiva#9]
Tienes una idea del porque me sale este error o como es que tengo que mardar lo solicitud de busqueda por uuid porque segun la documentacion no debo declara ni el rango de fechas ni el emisor ni solicitante

_Originally posted by @Charles9424 in https://github.com/AndresRamos/ARSoftware.Cfdi.DescargaMasiva/discussions/7#discussioncomment-5336598_

**Comment by Charles9424** [comment]
<s:Envelope xmlns:s=" [http://schemas.xmlsoap.org/soap/envelope/">](http://schemas.xmlsoap.org/soap/envelope/%22%3E) <s:Body><s:Fault>a:InternalServiceFaultError al deserializar el cuerpo del mensaje de solicitud para la operación 'SolicitaDescarga'. La cadena '' no es un valor AllXsd válido. en System.Xml.Schema.XsdDateTime..ctor(String text, XsdDateTimeFlags tipos)

esta es la respueta 

en System.Xml.XmlConvert.ToDateTime(String s, XmlDateTimeSerializationMode dateTimeOption)
en Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderISolicitaDescargaService.Read18_SolicitudDescargaMasivaTercero(Boolean isNullable, Boolean isNullable checkType)
en Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderISolicitaDescargaService.Read21_SolicitaDescarga()
en System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)System.FormatExceptionHay un error en el documento XML (1, 366). en System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
en System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parámetros, Boolean isRequest)System.InvalidOperationExceptionError al deserializar el cuerpo del mensaje de solicitud para la operación 'SolicitaDescarga'. en System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parámetros, Boolean isRequest)
en System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(lector de XmlDictionaryReader, versión de MessageVersion, acción de cadena, MessageDescription messageDescription, Object[] parámetros, Boolean isRequest)
en System.ServiceModel.Dispatcher.OperationFormatter.DeserializeBodyContents(Message message, Object[] parámetros, Boolean isRequest)
en System.ServiceModel.Dispatcher.OperationFormatter.DeserializeRequest(Message message, Object[] parámetros)
en System.ServiceModel.Dispatcher.DispatchOperationRuntime.DeserializeInputs(MessageRpc& rpc)
en System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
en System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
en System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
en System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)System.ServiceModel.CommunicationException</s:Fault></s:Body></s:Envelope >

**Comment by Charles9424** [comment]
El codigo es similiar al que usas de ejemplo pero transformado a web services

**Comment by Charles9424** [comment]
public async Task<string> Descarga_Masiva_UUID([FromBody] Models.Input ahrm_request)
        {
            string ls_conversion = "";
            string[] args = null;
            string log_Services = null;
            string update_uuid = null;
            Models.Ouput Content = new Models.Ouput();
            try
            {
                IHost host = Host.CreateDefaultBuilder(args).ConfigureServices(services =>
                {
                    // Registrar servicios de descarga masiva con el contenedor de servicios
                    services.AddCfdiDescargaMasivaServices();
                })
                    .Build();
                CancellationTokenSource cancellationTokenSource = new();
                CancellationToken cancellationToken = cancellationTokenSource.Token;

                await host.StartAsync(cancellationToken);
                // Parametros
                string Ruta_Temp = Path.GetTempPath();
                string Ruta_Carpeta = Ruta_Temp + @"Descarga_CFDI\";
                System.IO.Directory.CreateDirectory(Ruta_Carpeta);
                byte[] Certificado_byte = Convert.FromBase64String(ahrm_request.Certificado_base64);
                System.IO.File.WriteAllBytes(Ruta_Carpeta + "Certificado.cer", Certificado_byte);

                byte[] Key_Byte = Convert.FromBase64String(ahrm_request.Key_base64);
                System.IO.File.WriteAllBytes(Ruta_Carpeta + "Key.key", Key_Byte);
                string Uuid = ahrm_request.Uuid;

                var certificadoPassword = ahrm_request.Contraseña;
                DateTime fechaInicio = (DateTime)ahrm_request.Fecha_Inicio;

                // Fecha Fin
                 DateTime fechaFin = (DateTime)ahrm_request.Fecha_Fin;

                //Tipo de Solicitud
                TipoSolicitud? tipoSolicitud = Validar_Tipo_Comprobante.Validar_solicitud(ahrm_request.Tipo_Solicitud);

                // Tipo de Comprovante
                TipoComprobante? tipocomprobante = Validar_Tipo_Comprobante.Validar(ahrm_request.Tipo_Comprobante);

                // RFC
                // var rfcEmisor = "";
                string rfcEmisor = ahrm_request.RFC_Emisor;
                var rfcReceptores = new List<string> { ahrm_request.RFC_Receptor };
                string rfcSolicitante = ahrm_request.RFC_Solicitante;
                string RfcACuentaTerceros = ahrm_request.RFC_Terceros;
                string rutaDescarga = Ruta_Carpeta + @"Descarga\";
                string Nombre_Fecha_Inicio = fechaInicio.ToString("ddMMyyyy");
                string Nombre_Fecha_Fin = fechaFin.ToString("ddMMyyyy");
                string ruta_descomprecion_cfdi = rutaDescarga + ahrm_request.Tipo_Comprobante + "_" + Nombre_Fecha_Inicio + "_" + Nombre_Fecha_Fin + ".zip";
                DateTime Fecha_Actual = DateTime.Now;

                var logger = host.Services.GetRequiredService<ILogger<Program>>();
                int Carga_Encabezado_CFDI = MySql.Cargar_Detalle_CFDI.Carga_Encabezado_CFDI(Fecha_Actual, tipocomprobante, fechaInicio, fechaFin, ruta_descomprecion_cfdi, "0", "Web_services", "Prueba");

                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "0", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-INICIO");

                App_Data.Parametros_PFX oPfx = new App_Data.Parametros_PFX(Ruta_Carpeta + "Certificado.cer", Ruta_Carpeta + "Key.key", certificadoPassword, Ruta_Carpeta + "PFX.pfx", Ruta_Carpeta);
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREACION_PFX");


                if (!oPfx.creaPFX())
                {
                    log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "-1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREACION_PFX");
                    return "Error al crear PFX";
                }

                byte[] certificadoPfx = await System.IO.File.ReadAllBytesAsync(Ruta_Carpeta + "PFX.pfx", cancellationToken);


                //Cargar encabezado 

                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREACION_CERTIFICADO_PFX");

                X509Certificate2 certificadoSat = X509Certificate2Helper.GetCertificate(certificadoPfx, certificadoPassword);

                // Autenticacion
                var autenticacionService = host.Services.GetRequiredService<IAutenticacionService>();


                var autenticacionRequest = AutenticacionRequest.CreateInstance();

                //Enviando solicitud de autenticacion.
                AutenticacionResult autenticacionResult = await autenticacionService.SendSoapRequestAsync(autenticacionRequest, certificadoSat, cancellationToken);
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREANDO_AUTENTIFICACION");
                Content.cadena_resultado = autenticacionResult.ResponseContent;

                if (!autenticacionResult.AccessToken.IsValid)
                {
                    /*logger.LogError("La solicitud de autenticacion no fue exitosa. FaultCode:{0} FaultString:{1}",
                        autenticacionResult.FaultCode,
                        autenticacionResult.FaultString);*/
                    Content.clave_estatus_message = autenticacionResult.FaultString;
                    Content.clave_estatus_code = autenticacionResult.FaultCode;
                    Content.cadena_resultado = autenticacionResult.ResponseContent;

                    log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "-1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-AUTENTIFICACION_ERRONEA");

                    return JsonConvert.SerializeObject(Content);

                }
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-AUTENTIFICACION_CREADA");


                // Solicitud
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREANDO_SOLICITUD_SOLICITUD_DESCARGA");

                var solicitudService = host.Services.GetRequiredService<ISolicitudService>();
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREANDO_SOLICITUD_SOLICITUD_DESCARGA");


                //var solicitudRequest = SolicitudRequest.CreateInstance(
                //    null /*FECHA INICIO*/,
                //    null /*FECHA FIN*/,
                //    tipoSolicitud,
                //    "",
                //    rfcReceptores,
                //    "",
                //    RfcACuentaTerceros,
                //    autenticacionResult.AccessToken,
                //    tipocomprobante,
                //    Uuid
                //    );
                var solicitudRequest = SolicitudRequest.CreateInstance(fechaInicio, fechaFin, tipoSolicitud, rfcEmisor, rfcReceptores, rfcSolicitante, RfcACuentaTerceros, autenticacionResult.AccessToken, tipocomprobante, Uuid);



                logger.LogInformation("Enviando solicitud de solicitud de descarga.");
                SolicitudResult solicitudResult = await solicitudService.SendSoapRequestAsync(solicitudRequest, certificadoSat, cancellationToken);

                // update_uuid = MySql.Cargar_Detalle_CFDI.Update_Uuid(Carga_Encabezado_CFDI, Content.uuid);

                if (string.IsNullOrEmpty(solicitudResult.RequestId))
                {

                    log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "-1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-ERROR_SOLICITUD_SOLICITUD_DESCARGA_NO_EXITOSA");

                    /*logger.LogError("La solicitud de solicitud de descarga no fue exitosa. RequestStatusCode:{0} RequestStatusMessage:{1}",
                        solicitudResult.RequestStatusCode,
                        solicitudResult.RequestStatusMessage);*/
                    throw new Exception();

                }

                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-ERROR_SOLICITUD_SOLICITUD_DESCARGA_EXITOSA");

                // Verificacion
                //logger.LogInformation("Buscando el servicio de verificacion en el contenedor de servicios (Dependency Injection).");
                var verificaSolicitudService = host.Services.GetRequiredService<IVerificacionService>();

                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREANDO_SOLICITUD_VERIFIACION");
                var verificacionRequest = VerificacionRequest.CreateInstance(solicitudResult.RequestId, null, autenticacionResult.AccessToken);

                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-ENVIANDO_SOLICITUD_VERIFIACION");
                VerificacionResult verificacionResult = await verificaSolicitudService.SendSoapRequestAsync(verificacionRequest, certificadoSat, cancellationToken);
                // Content.uuid = solicitudResult.RequestId;

                Content.estatus_sat = verificacionResult.DownloadRequestStatusNumber;

                if (verificacionResult.DownloadRequestStatusNumber != EstadoSolicitud.Terminada.Value.ToString())
                {
                    /*
                    logger.LogError(
                        "La solicitud de verificacion no fue exitosa. DownloadRequestStatusNumber:{0} RequestStatusCode:{1} RequestStatusMessage:{2}",
                        verificacionResult.DownloadRequestStatusNumber,
                        verificacionResult.RequestStatusCode,
                        verificacionResult.RequestStatusMessage);
                    */
                    log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "-1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-SOLICITUD_VERIFICACION_NO_EXITOSA");
                    Content.clave_estatus_message = solicitudResult.RequestStatusMessage;
                    Content.clave_estatus_code = solicitudResult.RequestStatusCode;
                    Content.cadena_resultado = solicitudResult.ResponseContent;


                    if (verificacionResult.DownloadRequestStatusNumber == EstadoSolicitud.Aceptada.Value.ToString())
                    {
                        /*
                        logger.LogInformation(
                            "Es estado de la solicitud es Aceptada. Mandar otra solicitud de verificaion mas tarde para que el servicio web pueda procesar la solicitud.");
                        */
                        log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "-1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-SOLICITUD_ACEPTADA_MADAR_OTRA_SOLICITUD_DESPUES");
                        Content.clave_estatus_message = solicitudResult.RequestStatusMessage;
                        Content.clave_estatus_code = solicitudResult.RequestStatusCode;
                        Content.cadena_resultado = solicitudResult.ResponseContent;

                        return JsonConvert.SerializeObject(Content);
                    }
                    else if (verificacionResult.DownloadRequestStatusNumber == EstadoSolicitud.EnProceso.Value.ToString())
                    {
                        /*
                        logger.LogInformation(
                            "Es estado de la solicitud es En Proceso. Mandar otra solicitud de verificaion mas tarde para que el servicio web pueda procesar la solicitud.");
                        */
                        log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "-1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-SOLICITUD_PENDIENTE_MADAR_OTRA_SOLICITUD_DESPUES");
                        Content.clave_estatus_message = solicitudResult.RequestStatusMessage;
                        Content.clave_estatus_code = solicitudResult.RequestStatusCode;
                        Content.cadena_resultado = solicitudResult.ResponseContent;
                        return JsonConvert.SerializeObject(Content);
                    }

                    return JsonConvert.SerializeObject(Content);
                }
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-SOLICITUD_VERIFICACION_EXITOSA");


                foreach (string idsPaquete in verificacionResult.PackageIds)
                {
                    logger.LogInformation("PackageId:{0}", idsPaquete);
                }

                // Descarga
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-BUSCANDO_SERVICIO_VERIFICACION");

                // logger.LogInformation("Buscando el servicio de verificacion en el contenedor de servicios (Dependency Injection).");
                var descargarSolicitudService = host.Services.GetRequiredService<IDescargaService>();

                foreach (string? idsPaquete in verificacionResult.PackageIds)
                {
                    log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-CREANDO_SOLICITUD_DESCARGA");

                    //    logger.LogInformation("Creando solicitud de descarga.");
                    var descargaRequest = DescargaRequest.CreateInstace(idsPaquete, rfcSolicitante, autenticacionResult.AccessToken);

                    log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-ENVIANDO_SOLICITUD_DESCARGA");

                    //    logger.LogInformation("Enviando solicitud de descarga.");
                    DescargaResult? descargaResult = await descargarSolicitudService.SendSoapRequestAsync(descargaRequest, certificadoSat, cancellationToken);

                    string fileName = Path.Combine(rutaDescarga, $"{idsPaquete}.zip");
                    byte[] paqueteContenido = Convert.FromBase64String(descargaResult.Package);
                    string st_ruta_Archivo = rutaDescarga + @"\" + idsPaquete.ToString();

                    if (!Directory.Exists(st_ruta_Archivo))
                    {
                        Directory.CreateDirectory(rutaDescarga);
                        Console.WriteLine("Carpeta Creada");
                    }

                    log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-GUARDANDO_ARCHIVO");

                    logger.LogInformation("Guardando paquete descargado en un archivo .zip en la ruta de descarga.");
                    // using FileStream fileStream = System.IO.File.Create(fileName, paqueteContenido.Length);
                    System.IO.File.WriteAllBytes(ruta_descomprecion_cfdi, paqueteContenido);
                    // await fileStream.WriteAsync(paqueteContenido, 0, paqueteContenido.Length, cancellationToken);
                    string Update_Encabezado = MySql.Cargar_Detalle_CFDI.Update_Encabezado(Carga_Encabezado_CFDI);

                    Content.ubicacion_descarga = st_ruta_Archivo;
                }
                await host.StopAsync(cancellationToken);
                log_Services = MySql.WS_LOG.WS_SAVE_LOG(Carga_Encabezado_CFDI, "1", "CFDI", DateTime.Now, "DESCARGA/MASIVA_CFDI-FIN");


                return JsonConvert.SerializeObject(Content);

**Comment by AndresRamos** [comment]
Me falta hacer un ejemplo yo pero viendo el mensaje de error puedo ver que dice que no puede deserializar una fecha.

Revisando tu XML se me hacer raro `FechaFinal`.

 ```xml
<des:solicitud FechaInicial="" FechaFinal="2" RfcSolicitante="" TipoSolicitud="CFDI" TipoComprobante="P" UUID="222222-2222-2222-2222-2222222">
```

Por que `FechaFinal="2"`?

**Comment by Charles9424** [comment]
La fecha se manda nula tambien la fecha final y ese dos fue por error de dedo

**Comment by Charles9424** [comment]
Tambien sin mandar los nodos de FechaInicial y FechaFinal

**Comment by AndresRamos** [comment]
Leyendo la documentacion del SAT:

> UUID | Parámetro obligatorio. En caso de utilizarse este parámetro no deben declararse los siguientes criterios de búsqueda: FechaInicial, FechaFinal, RfcEmisor y RfcSolicitante.

Mi duda ahorita es: ¿se deben dejar en blanco o no incluirlos en el XML?

Tambien vi esto en un foro:

> Logre descargar por UUID: 
> El campo se nombra como Folio NO UUID en el xml adicionalmente remuevan el nodo de rfc receptor (<RfcReceptores/>) del xml: 
> `<solicitud Folio="" RfcSolicitante="" TipoSolicitud="CFDI">`

**Comment by AndresRamos** [comment]
Acabo de liberar una version beta en [NuGet ](https://www.nuget.org/packages/ARSoftware.Cfdi.DescargaMasiva/2.1.0-beta1)que corrige este error. Podrias probarla?

Tambien genere un [Release 2.1.0-beta1](https://github.com/AndresRamos/ARSoftware.Cfdi.DescargaMasiva/releases/tag/2.1.0-beta1)

**Comment by Charles9424** [comment]
Okey muchas gracias lo pruebo y te aviso que tal va todo

**Comment by Charles9424** [comment]
Despues de hacer varias pruebas me marca como XML mal formado

<S11:Envelope xmlns:S11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<S11:Header />
    <S11:Body>
        <des:SolicitaDescarga>
            <des:solicitud RfcSolicitante="" TipoSolicitud="CFDI" Folio="22222222-2222-2222-2222-22222222">
                <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
                  <SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>4654564564654+RuRReLZumx8hfi4=</DigestValue></Reference>
                 </SignedInfo>
                <SignatureValue>Bsdasdasd
                </SignatureValue>
                    <KeyInfo>
                        <X509Data>
                            <X509IssuerSerial>
                                <X509IssuerName>asdasdasdasd
                                    </X509IssuerName>
                                    <X509SerialNumber>54546573248613545132456423</X509SerialNumber>
                            </X509IssuerSerial>
                            <X509Certificate>
                                Cetrificado
                            </X509Certificate>
                         </X509Data>
                    </KeyInfo>
                </Signature>
            </des:solicitud>
        </des:SolicitaDescarga>
    </S11:Body>
</S11:Envelope>

**Comment by Charles9424** [comment]
`<S11:Envelope xmlns:S11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<S11:Header />
    <S11:Body>
        <des:SolicitaDescarga>
            <des:solicitud RfcSolicitante="" TipoSolicitud="CFDI" Folio="22222222-2222-2222-2222-22222222">
                <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
                  <SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>4654564564654+RuRReLZumx8hfi4=</DigestValue></Reference>
                 </SignedInfo>
                <SignatureValue>Bsdasdasd
                </SignatureValue>
                    <KeyInfo>
                        <X509Data>
                            <X509IssuerSerial>
                                <X509IssuerName>asdasdasdasd
                                    </X509IssuerName>
                                    <X509SerialNumber>54546573248613545132456423</X509SerialNumber>
                            </X509IssuerSerial>
                            <X509Certificate>
                                Cetrificado
                            </X509Certificate>
                         </X509Data>
                    </KeyInfo>
                </Signature>
            </des:solicitud>
        </des:SolicitaDescarga>
    </S11:Body>
</S11:Envelope>`

**Comment by Charles9424** [comment]
`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <SolicitaDescargaResponse xmlns="http://DescargaMasivaTerceros.sat.gob.mx">
        <SolicitaDescargaResult IdSolicitud="22222-2222-2222-2222-225252525" CodEstatus="5004" Mensaje="No se encontro la informacion"/>
    </SolicitaDescargaResponse>
    </s:Body>
</s:Envelope>`

**Comment by Charles9424** [comment]
Con otros pruebas me marcaba que no habia informacion

**Comment by AndresRamos** [comment]
Yo realize pruebas y si me trae el CFDI. 

El `RequestingRfc` que es el RFC solicitante es obligatorio.

```csharp
logger.LogInformation("Buscando el servicio de solicitud de descarga en el contenedor de servicios (Dependency Injection).");
var solicitudService = host.Services.GetRequiredService<ISolicitudService>();

logger.LogInformation("Creando solicitud de solicitud de descarga.");
var solicitudPorUuid = SolicitudRequest.CreateInstance(uuid, rfcSolicitante, autenticacionResult.AccessToken);

logger.LogInformation("Enviando solicitud de solicitud de descarga.");
SolicitudResult solicitudResult = await solicitudService.SendSoapRequestAsync(solicitudPorUuid, certificadoSat, cancellationToken);
```

**Comment by Charles9424** [comment]
Muchas gracias ya puede hacer la descarga por CFDI muchas gracias por el apoyo
